version: '3.8'

services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: imp_db
      POSTGRES_USER: imp_user
      POSTGRES_PASSWORD: imp_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # backend:
  #   build: .
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     DATABASE_URL: postgresql+asyncpg://imp_user:imp_password@db:5432/imp_db
  #   depends_on:
  #     - db
  #   volumes:
  #     - .:/app
  #   command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data: